name: CI

on: [push, pull_request]

jobs:
  lint-and-sim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Verilator
        run: |
          sudo apt-get install -y git autoconf flex bison libfl2 libfl-dev help2man
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout v5.048
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install


      - name: Install cocotb
        run: pip install cocotb

      - name: Run lint
        run: make lint

      - name: Run sim
        run: make -B sim